---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../redhat
patches:
  - target:
      group: appstudio.redhat.com
      version: v1alpha1
      kind: EnterpriseContractPolicy
    path: policies.yaml
  - target:
      group: appstudio.redhat.com
      version: v1alpha1
      kind: EnterpriseContractPolicy
    patch: |-
      - op: replace
        path: /metadata/name
        value: product-one
      - op: replace
        path: /spec/description
        value: This is the policy config for product-one.

